### PR TITLE
Fix #121 and add a test

### LINKED ISSUE #121: AwsClientTracing: Null pointer exception thrown for AwsAsyncClientBuilders
Stack trace includes:
```
Caused by: java.lang.NullPointerException: null
	at brave.instrumentation.aws.AwsClientTracing$TracingExecutorFactory.<init>(AwsClientTracing.java:69)
	at brave.instrumentation.aws.AwsClientTracing.build(AwsClientTracing.java:47)
```

This is because the `getClientConfiguration()` does not get initialized by default in the default builder (thus blows up when calling `clientConfiguration.getMaxConnections()` in `TracingExecutorFactory`), instead Amazon uses `AwsSyncClientParams` to provide defaults if any are missing right before they call the build method:

```
    @Override
    public final TypeToBuild build() {
        return configureMutableProperties(build(getSyncClientParams()));
    }
```

Temporary work-around: Have async builders include: `.withClientConfiguration(new ClientConfigurationFactory().getConfig());`

### PR DESCRIPTION
**Pull request by devinsba**
fixes #121

### CODE REVIEW

File: brave-instrumentation/aws-java-sdk-core/src/test/java/brave/instrumentation/aws/AwsClientTracingTest.java [hunk 1]
```diff
@@ -94,6 +102,16 @@ public void testSpanCreatedAndTagsApplied() throws InterruptedException {
...
 
+  @Test
+  public void buildingAsyncClientWithEmptyConfigDoesNotThrowExceptions() {
+    Tracing tracing = tracingBuilder().build();
+    HttpTracing httpTracing = HttpTracing.create(tracing);
+    environmentVariables.set("AWS_REGION", "us-east-1");
+
+    AmazonDynamoDBAsync asyncClient =
+        AwsClientTracing.create(httpTracing).build(AmazonDynamoDBAsyncClientBuilder.standard());
+  }
```
Comment (devinsba) [inline brave-instrumentation/aws-java-sdk-core/src/test/java/brave/instrumentation/aws/AwsClientTracingTest.java]: @sdavids13 can you please validate this test is what you meant in the issue you filed

Comment (sdavids13) [reply brave-instrumentation/aws-java-sdk-core/src/test/java/brave/instrumentation/aws/AwsClientTracingTest.java]: 👍

**Comment by adriancole** [comment]
thx!
